### PR TITLE
feat: support test filtering via karma args

### PR DESCRIPTION
**Pull request by marcins**
Add support for providing a QUnit test filter string via Karma client config.

### CODE REVIEW

**Comment by marcins** [comment]
I signed it!

On 15 October 2015 at 16:13, googlebot <notifications@github.com> wrote:

> Thanks for your pull request. It looks like this may be your first
> contribution to a Google open source project, in which case you'll need to
> sign a Contributor License Agreement (CLA).
>
> [image: :memo:] *Please visit https://cla.developers.google.com/
> <https://cla.developers.google.com/> to sign.*
>
> Once you've signed, please reply here (e.g. I signed it!) and we'll
> verify. Thanks.
> ------------------------------
>
>    - If you've already signed a CLA, it's possible we don't have your
>    GitHub username or you're using a different email address. Check your
>    existing CLA data <https://cla.developers.google.com/clas> and verify
>    that your email is set on your git commits
>    <https://help.github.com/articles/setting-your-email-in-git/>.
>    - If you signed the CLA as a corporation, please let us know the
>    company's name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/karma-runner/karma-qunit/pull/29#issuecomment-148283059>
> .
>



-- 
M.

**Comment by maksimr** [comment]
@marcins Thanks!

What about change `filter` on `grep`? Because now `grep` used in [mocha](https://github.com/karma-runner/karma-mocha#configuration) and [jasmine](https://github.com/karma-runner/karma-jasmine) for filtering tests. It will be nice have unified interface for filtering between different test frameworks

**Comment by marcins** [comment]
@maksimr - that would be a change to qunit itself, not karma-qunit as quint implements the filter check as an `.indexOf` check against the full name of the test: https://github.com/jquery/qunit/blob/64fdbac15474eedf22f1be5b2ecd5b0dbbe61a16/src/test.js#L392-L407

If qunit ever supports a regex based filter using the config property then this change to karma-qunit will continue to work.

**Comment by jvdl** [comment]
Looks good, would love to see this merged. Would be super useful for us to be able to run a single module/test. Thanks @marcins!

**Comment by mduvall** [comment]
Hello,

I have opened https://github.com/karma-runner/karma-qunit/pull/30 that enables all configuration values to be passed transparently to `window.QUnit`. I initially tried out this commit and felt a bit uneasy that `config.filter` is an undocumented configuration key (see the documentation [here](https://api.qunitjs.com/QUnit.config/), @marcins does point to valid code but they appear to be internals).

While I agree that the top-level testing interface would be preferable, this seems to pin Karma clients to a specific version of the testing framework (in this case QUnit) as the keys are pinned here by hand. I would like to propose an alternate solution in #30 that enables Karma clients to define their own configuration for QUnit and have it be passed as such.

Thoughts?

**Comment by zzo** [comment]
Agreed #30 seems like a better idea

**Comment by marcins** [comment]
Yep, I'm happy with your more general approach @mduvall!

**Pull request closed without merging**
