### PR TITLE
Update karma to ^5.0.1

### LINKED ISSUE #137: Karma 5.x support
Karma 5 was released recently. Please add support for 5.x version.

### PR DESCRIPTION
**Pull request by jdforrester**
Fixes #137

### CODE REVIEW

**Comment by XhmikosR** [comment]
This has unrelated patches...

**Comment by jdforrester** [comment]
Happy to explicitly point out the CVEs you're leaving unpatched if that's the method prefered for this repo?

**Comment by XhmikosR** [comment]
[Not](https://github.com/karma-runner/karma-qunit/pull/141) leaving anything out. You should keep your PRs clean.

**Comment by jdforrester** [comment]
> [Not](https://github.com/karma-runner/karma-qunit/pull/141) leaving anything out. You should keep your PRs clean.

OK, sure, manually-pointed PRs at each other works, but is horrible for you as a reviewer. I suppose we have to make-do.

**Comment by XhmikosR** [comment]
I just want things done, I don't have time to sugarcoat things, sorry.

**Pull request closed without merging**
