### PR TITLE
fix (adapter): save and reset qunit-fixture properly

### PR DESCRIPTION
**Pull request by asapach**
As mentioned in #104, [`QUnit.begin()` handler](https://github.com/qunitjs/qunit/blob/89dcd90211fb129df48aa11b72dbafd9f5a18009/runner/fixture.js#L27) runs first for `QUnit` and then for `karma-qunit` adapter. `QUnit` saves any existing `#qunit-fixture` element as `QUnit.config.fixture`; if none exist at this point, `#qunit-fixture` will never be reset [during `QUnit.testStart()`](https://github.com/qunitjs/qunit/blob/89dcd90211fb129df48aa11b72dbafd9f5a18009/runner/fixture.js#L50). `karma-qunit` runs too late to affect that, but it can create the missing `#qunit-fixture` element and set `QUnit.config.fixture` to an empty string ([as documented](http://api.qunitjs.com/config/QUnit.config)) to be reset properly.

//CC @Krinkle

### CODE REVIEW

**Comment by asapach** [comment]
Could you please publish a new release?

**Comment by Johann-S** [comment]
I cannot publish to NPM I don't have the rights, maybe @johnjbarton can handle that 👍

**Comment by dignifiedquire** [comment]
published a new version from master

**Comment by Johann-S** [comment]
@dignifiedquire why did you the version number to `v2.1.0` as it's just a bug fix ? 🤔 IMO `v2.0.3` would be enough here

**Comment by dignifiedquire** [comment]
because I made a typo and realised it too late :( you are right, it should have been a patch version

**Comment by asapach** [comment]
Thanks for the release anyway :)

**Comment by Johann-S** [comment]
That's something happen 😄

**Pull request merged**
