### PR TITLE
chore: release v4.2.0

### PR DESCRIPTION
**Pull request by Krinkle**

### CODE REVIEW

**Comment by Krinkle** [comment]
@XhmikosR Would you mind publishing this to npm and/or adding me as co-owner for the package? I've already merged and tagged the release, but it still needs an `npm publish` from a git checkout (this release equates latest master as of this moment)

**Comment by XhmikosR** [comment]
Hey, @Krinkle. Do you have the commands I need to run?

On a side note, I wouldn't remove anything in minor version because it's technically a breaking change. I suggest that you revert the removal, make it a patch version 4.2.1 and if you want to remove something bump the version to 5.

**Comment by Krinkle** [comment]
@XhmikosR This doesn't "remove" something (I think?). It changes the internal karma-qunit code to not make use of a deprecated feature. It "removes" a needless call to the QUnit.load function. It still works the same way either way, since `QUnit.load` is superseded by `QUnit.start`.

The command to add co-owners to an npm package is <https://docs.npmjs.com/cli/v6/commands/npm-owner>:

```
$ cd karma-qunit/
karma-qunit$ npm owner add krinkle
```

or

```
$ npm owner add krinkle karma-qunit
```

**Comment by XhmikosR** [comment]
Done!

```
npm notice INFO: User krinkle invited to package karma-qunit successfully.
+ krinkle (karma-qunit)
```

**Pull request merged**
