### PR TITLE
Add karma in peerDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by Johann-S** [comment]
Since we don't support Node 6, I think we should bump Karma to v4

**Comment by XhmikosR** [comment]
I don't see this from the current .travis.yml.

**Comment by Johann-S** [comment]
You're right my bad 👍

**Comment by XhmikosR** [comment]
And also, I don't want to leave people who stick with karma 3.x out. Because that's what happened with karma 4.x. All 3.x users get the npm vulnerabilities.

So, mys suggestion is https://github.com/karma-runner/karma-qunit/pull/108#issuecomment-478475898

After the minor release we can make a new major release dropping Node.js 6 later.

**Pull request merged**
