### PR TITLE
karma v2 + unit test fixes

### PR DESCRIPTION
**Pull request by masubi**

### CODE REVIEW

**Comment by masubi** [comment]
I signed it!

**Comment by masubi** [comment]
these were authored by me and change was authored by @dotch

**Comment by dotch** [comment]
Feel free to just replace my commit!

**Comment by dignifiedquire** [comment]
Thank you, could you please update the commit messages to follow our [convention](http://karma-runner.github.io/1.0/dev/git-commit-msg.html)?

**Comment by masubi** [comment]
going to close and re-open since it won't let me get rid of previous commit + will update commit messages

**Pull request closed without merging**
