### PR TITLE
Dev patches

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
We need to replace Travis with GitHub Actions, it's too slow...

**Comment by Krinkle** [comment]
Can probably change to unconditionally use Firefox (or FirefoxHeadless) here:

https://github.com/karma-runner/karma-qunit/blob/6c237ca7291621fd2701e6625d70f0d9ff3e4be7/karma.conf.js#L10

**Comment by XhmikosR** [comment]
I changed that but the issue is with the `DISPLAY` env variable. I've split the Action patch to another branch https://github.com/karma-runner/karma-qunit/compare/actions where you can see the failures.

**Comment by Krinkle** [comment]
> I changed that but the issue is with the `DISPLAY` env variable.

Yeah, because it's using the regular graphical mode, which expects either a real monitor or an X11/Xvfb display.

Use the Headless variant to make this simpler, both for local, Travis, or indeed GitHub.

**Comment by XhmikosR** [comment]
OK, I will try using `FirefoxHeadless` and drop the `DISPLAY` env var and see how it goes. If it works, I'll merge the Actions patch to this branch.

**Comment by XhmikosR** [comment]
Firefox headless works now but Chrome fails. I tried `process.env.CI ? ['ChromeHeadless'] : ['Chrome']` but still fails.

**Comment by XhmikosR** [comment]
I'm going to merge this and release a new patch version. Later we can update the rest of the deps and drop Node.js 8.x from CI.

**Pull request merged**
