### PR TITLE
fix-115-array-error

### LINKED ISSUE #115: JS coding in 2.1.0 when first test fails
JS runtime throws 
`TypeError: testResult.errors is undefined\nat node_modules/karma-qunit/lib/adapter.js:99`
when first test fails.

relevant src code snippet is
~~~
runner.log(function (details) {
      if (!details.result) {
        
// ...
        testResult.success = false
        testResult.errors.push(msg) // <- the array.push fails
      }
    })
~~~

Environment:
karma-qunit 2.1.0
karma 3.1.1
qUnit 2.6.1
node 11.1.0
macOS 10.14.2

**=> I will provide a PR fixing this!**

### PR DESCRIPTION
**Pull request by vobu**
Fixes #115

### CODE REVIEW

**Comment by Johann-S** [comment]
Any concers here @Krinkle, @johnjbarton or @XhmikosR ?

**Comment by vobu** [comment]
> That line can be changed https://github.com/karma-runner/karma-qunit/pull/116/files#diff-e52a9a67956bd51d044af4058fb939ceR103
> 
> to :
> 
> ```js
> log: testResult.errors,
> ```

sorry, missed this one in your original answer. updated now.

**Comment by vobu** [comment]
Hi guys,

any news on potentially merging this? Somewhat waiting for it as this would eliminate an error root cause in one of our projects.

Thx! -V.

**Comment by vobu** [comment]
hey, just wanted to check in with you guys @Johann-S et al to see how things are for this PR - would really like to use the updated code base. thx, v.

**Comment by vobu** [comment]
Thx for the merge!
Could you guys please also bump and release the npm module?

**Comment by XhmikosR** [comment]
I don't think I can do this myself, unfortunately.

**Comment by vobu** [comment]
> I don't think I can do this myself, unfortunately.

then who has the power :) ? pinging @Johann-S and @dignifiedquire

**Comment by XhmikosR** [comment]
Personally I'd like #108 merged before making a new release.

**Pull request merged**
